#! /bin/bash
./client $(ps | grep server | awk 'NR==2{print$1}') "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent hendrerit nulla tellus, nec semper tortor scelerisque nec. Vivamus sagittis nibh sit amet nibh porta tincidunt. Nunc pretium augue non massa laoreet pulvinar eget nec nulla. Phasellus nec pretium mauris, vel interdum tellus. Sed maximus porta sapien sit amet egestas. Aliquam vestibulum, nisl bibendum scelerisque consectetur, dolor orci ullamcorper velit, at vulputate felis lorem id massa. Nam tristique quis sapien eu hendrerit. Cras mattis laoreet nisl eget accumsan.

Vestibulum ac magna euismod, congue arcu varius, commodo diam. Sed purus nunc, porttitor at lacinia id, mollis sed sem. Maecenas non sagittis massa, tempor porta neque. Praesent efficitur luctus ultricies. Mauris non aliquam dui. Vivamus rutrum scelerisque felis, quis scelerisque nunc ultricies sit amet. Suspendisse et sagittis risus. Fusce sollicitudin urna eu facilisis vestibulum. Donec et arcu dignissim, interdum dolor in, convallis turpis. Suspendisse sed eros nibh.

Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec sit amet tristique urna, eu ultricies tellus. Vivamus id sagittis nibh, non laoreet quam. Integer rutrum vitae elit sed ullamcorper. Fusce nec imperdiet libero. Aenean eleifend nibh nunc, quis mattis sapien hendrerit non. Nulla facilisi. Pellentesque ut mauris quis augue malesuada pharetra. Vestibulum eleifend venenatis sem venenatis blandit. Aenean accumsan quis magna ac malesuada. Aliquam tempor, augue eleifend interdum aliquam, leo ex ornare odio, ut tempus dolor enim sit amet est. Praesent a blandit arcu, sed vehicula tortor. Fusce dui urna, porta et nisi vestibulum, iaculis eleifend augue. Donec bibendum massa ac arcu tempor dapibus.

Phasellus quam tortor, scelerisque eget dolor ac, laoreet vehicula justo. Sed eros neque, ultrices vel dolor eget, sagittis pulvinar sapien. Integer iaculis porta mattis. Nam venenatis, nisl sed posuere sollicitudin, ante sapien consectetur purus, vitae mattis enim mauris ac ipsum. Nunc volutpat sapien elit, gravida laoreet ante porttitor efficitur. Integer non nibh porttitor, bibendum leo in, rutrum urna. Cras est dui, convallis et neque ac, fringilla ultricies nibh.

Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent porta sed arcu eu tincidunt. Nullam efficitur, purus a dignissim facilisis, libero augue euismod augue, eget tristique sem tortor a mi. Integer interdum magna in feugiat euismod. Phasellus vitae mi tellus. Sed eget fermentum justo. Sed tempus nisl id venenatis interdum. Nunc ultricies turpis nibh. Duis condimentum dolor sit amet tellus blandit, eleifend laoreet metus luctus.

Nunc elit est, sagittis ac massa at, pulvinar egestas elit. Proin nulla metus, hendrerit quis euismod a, tempor et mi. Duis nisl ligula, sagittis pulvinar dolor in, lobortis facilisis dolor. Cras mollis nibh ac magna lacinia pellentesque. Nulla feugiat porttitor ipsum, quis bibendum elit. Donec auctor vitae odio eget feugiat. Sed malesuada lacus a elit scelerisque faucibus. Donec accumsan euismod magna, id molestie erat aliquam sed. Aliquam erat volutpat. Ut sed finibus nibh. Pellentesque at lacinia velit. Praesent non faucibus eros.

Duis ac congue arcu. Phasellus pellentesque varius blandit. Etiam tempus nec mauris nec euismod. Nam ac neque eget orci consequat tincidunt ut et arcu. Proin porttitor justo eu neque pulvinar congue. Sed eget orci malesuada, auctor ex sed, finibus leo. Etiam lectus ante, luctus id blandit a, dapibus ac sem. Proin cursus at tellus at mattis. Cras sit amet iaculis enim. Ut in egestas mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam tempor ullamcorper dapibus. Nullam mollis vitae dui ac rutrum. Vivamus volutpat tellus ut purus mollis egestas.

Curabitur turpis velit, mattis et ornare at, feugiat nec dolor. Suspendisse auctor bibendum odio in iaculis. Integer eu consequat ex. Maecenas bibendum in nisl ac maximus. Integer vestibulum maximus ornare. Maecenas lacinia ultrices leo, nec venenatis odio mattis sed. Mauris pharetra nibh lectus, quis porta ipsum mollis non. Vestibulum a semper justo, sed dapibus urna. Cras id arcu bibendum, tristique metus non, pretium mi. Proin eu justo consequat, dignissim mauris vitae, rutrum risus.

Ut mattis eu tellus non tristique. Vivamus mattis molestie tellus, in eleifend tellus viverra at. Suspendisse vitae elit non ante volutpat sodales. Cras id elit sagittis, vestibulum turpis vel, dictum nisl. Phasellus a nulla venenatis, dictum diam id, tristique lorem. In imperdiet, risus quis porttitor semper, mauris urna rhoncus velit, eget aliquam felis orci in diam. Vestibulum dapibus sed elit eu ultrices. Phasellus ut urna sit amet justo pellentesque viverra id eget nisi. Nunc ac lorem tincidunt, elementum mi vel, facilisis dui.

Aenean sodales tincidunt est id placerat. Donec vel risus eu libero gravida rutrum sit amet in ligula. Mauris dignissim mattis justo sed sagittis. Vivamus porta ante."